// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PluginCategory string

const (
	PluginCategoryAiAgent PluginCategory = "ai-agent"
	PluginCategoryPlugin  PluginCategory = "plugin"
	PluginCategoryApp     PluginCategory = "app"
)

func (e *PluginCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PluginCategory(s)
	case string:
		*e = PluginCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for PluginCategory: %T", src)
	}
	return nil
}

type NullPluginCategory struct {
	PluginCategory PluginCategory
	Valid          bool // Valid is true if PluginCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPluginCategory) Scan(value interface{}) error {
	if value == nil {
		ns.PluginCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PluginCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPluginCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PluginCategory), nil
}

type Plugin struct {
	ID             interface{}
	Title          string
	Description    string
	ServerEndpoint string
	Category       PluginCategory
	Audited        bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type PluginApikey struct {
	ID        pgtype.UUID
	PluginID  interface{}
	Apikey    string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	Status    int32
}

type PluginPolicy struct {
	ID            pgtype.UUID
	PublicKey     string
	PluginID      interface{}
	PluginVersion string
	PolicyVersion int32
	Signature     string
	Recipe        string
	Active        bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type VaultToken struct {
	ID         pgtype.UUID
	TokenID    string
	PublicKey  string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
