// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TestRunStatus string

const (
	TestRunStatusQUEUED  TestRunStatus = "QUEUED"
	TestRunStatusRUNNING TestRunStatus = "RUNNING"
	TestRunStatusPASSED  TestRunStatus = "PASSED"
	TestRunStatusFAILED  TestRunStatus = "FAILED"
	TestRunStatusERROR   TestRunStatus = "ERROR"
)

func (e *TestRunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestRunStatus(s)
	case string:
		*e = TestRunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TestRunStatus: %T", src)
	}
	return nil
}

type NullTestRunStatus struct {
	TestRunStatus TestRunStatus `json:"test_run_status"`
	Valid         bool          `json:"valid"` // Valid is true if TestRunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TestRunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestRunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestRunStatus), nil
}

type TestRun struct {
	ID             pgtype.UUID        `json:"id"`
	PluginID       string             `json:"plugin_id"`
	ProposalID     pgtype.Text        `json:"proposal_id"`
	Version        pgtype.Text        `json:"version"`
	Status         TestRunStatus      `json:"status"`
	RequestedBy    string             `json:"requested_by"`
	ArtifactPrefix pgtype.Text        `json:"artifact_prefix"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
